name: Generate Snake

on:
  schedule: # 定期运行
    - cron: "0 0 * * *" # 每天午夜运行一次
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: HugoPhi
          outputs: dist/snake.svg

      - name: Push Snake to the `output` branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: main
          build_dir: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
